apache/commons-text

src/main/java/org/apache/commons/text/StringEscapeUtils.java, src/main/java/org/apache/commons/text/translate/CsvTranslators.java, src/main/java/org/apache/commons/text/translate/SinglePassTranslator.java, src/test/java/org/apache/commons/text/translate/SinglePassTranslatorTest.java
CvsEscaper/CvsUnescaper are currently inner classes of StringEscapeUtils and it does not seem like it is a proper place for them.
Since they are package-private, they can be safely moved lang.text.translate package.
Moreover it's possible make them more DRY by introducing SinlgePassTranslator as suggested in TODO.
=> [TEXT-56] Move CvsTranslators out of StringEscapeUtils and make them DRY

pom.xml
To support compiling against Java 9, the version of Jacoco must be upgraded.  This closes https://issues.apache.org/jira/browse/TEXT-60
=> TEXT-60: Upgrade Jacoco version for Java 9 compatibility

src/main/java/org/apache/commons/text/ExtendedMessageFormat.java
@chtompki your suggestion worked for me. These two changes fix the failing tests when I set Language to Brazilian Portuguese in Ubuntu, fixing TEXT-64. All tests pass when locale is reverted back to en.
=> TEXT-64: Use Category.FORMAT for Locale.getDefault() to fix test failures when locale not set to en

checkstyle.xml
With this rule change checkstyle will work fine on Windows and Linux both.
=> Fixed checkstyle rule 'File does not end with a newline' on windows

src/main/java/org/apache/commons/text/WordUtils.java, src/test/java/org/apache/commons/text/WordUtilsTest.java
@chtompki Adding support for UTF-16 surrogate pairs to WordUtils.initials. Characters outside BMP can be used now and also added unit tests for surrogate pairs .
=> TEXT-89: WordUtils.initials support for UTF-16 surrogate pairs

src/main/java/org/apache/commons/text/RandomStringGenerator.java, src/test/java/org/apache/commons/text/RandomStringGeneratorTest.java
*.withinRange()* now able to accept multiple ranges.
Ex.
```
final char [][] pairs = {{'a','z'},{'0','9'}};
RandomStringGenerator generator = new RandomStringGenerator.Builder().withinRange(pairs).build();
```
=> TEXT-97: RandomStringGenerator able to pass multiple ranges to .withinRange()

src/changes/changes.xml, src/main/java/org/apache/commons/text/ExtendedMessageFormat.java, src/test/java/org/apache/commons/text/ExtendedMessageFormatTest.java
Created this pull request from the patch provided by Benoît Moreau in [TEXT-106](https://issues.apache.org/jira/browse/TEXT-106).
Thanks for your contribution Benoît!
Cheers
Bruno
=> TEXT-106: Exception thrown in ExtendedMessageFormat using quotes with custom registry

src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java, src/main/java/org/apache/commons/text/similarity/JaroWinklerSimilarity.java, src/main/java/org/apache/commons/text/similarity/package-info.java, src/site/xdoc/userguide.xml, src/test/java/org/apache/commons/text/similarity/JaroWinklerDistanceTest.java, src/test/java/org/apache/commons/text/similarity/JaroWinklerSimilarityTest.java
Provide class `JaroWinklerSimilarity` to compute JW similarity (reuses protected methods of `JaroWinklerDistance`). Changed the implementation of `JaroWinklerDistance` as it was computing similarity instead of distance values. Improved handling of equal character sequences.
=> TEXT-104: Jaro Winkler Distance refers to similarity

src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java, src/test/java/org/apache/commons/text/similarity/JaroWinklerDistanceTest.java
This PR makes the Clirr report pass for 1.7. It keeps the new `JaroWinklerSimilarity` class, but reverts the change in `JaroWinklerDistance`. This way we keep backward feature and binary compatibility.
Also added `TODO`'s in the code for 2.0, and if others are OK with this pull request, I will create a Task ticket in JIRA for 2.0, so that when a release manager performs the release, s/he won't forget to look at the TODO and update the code.
@saschaszott I feel bad reverting part of your change, but it will be fully available in an upcoming 2.0 release :)
Cheers
Bruno
=> TEXT-104: deprecate JaroWinkler methods for 2.0, and fix clirr report

src/main/java/org/apache/commons/text/similarity/JaroWinklerSimilarity.java, src/test/java/org/apache/commons/text/similarity/JaroWinklerSimilarityTest.java
Comparing CharSequence using Object.equals will fail when the CharSequence implementation does not support this.
=> TEXT-151: Use StringUtils.equals to test for CharSequence equality.

src/changes/changes.xml, src/main/java/org/apache/commons/text/WordUtils.java, src/test/java/org/apache/commons/text/WordUtilsTest.java
Hi, I have added a test that show shows the infinite loop, and the code that fixes it.
In order to make the test pass, and not only make the infinite loop stop happening, more changes were needed because the code for TEXT-111 did not fix the replacement of 0 length matches when we have multiple matches.
=> TEXT-152 - new tests and fix for infinite loop

src/main/java/org/apache/commons/text/similarity/RegexTokenizer.java
Use of a static pattern avoids the compile step on each invocation.
Remove the use of CharSequence.toString() to pass to the
matcher(CharSequence) method. The String conversion is not needed.
Fix the javadoc header @code tag.
=> TEXT-156: Fix the RegexTokenizer to use a static Pattern.

src/changes/changes.xml, src/main/java/org/apache/commons/text/similarity/JaccardDistance.java, src/main/java/org/apache/commons/text/similarity/JaccardSimilarity.java, src/test/java/org/apache/commons/text/similarity/JaccardDistanceTest.java, src/test/java/org/apache/commons/text/similarity/JaccardSimilarityTest.java
The rounding to 2 decimal places in the JaccardSimilarity prevents correct ranking of moderate length dissimilar strings.
=> TEXT-157: Remove rounding from JaccardSimilarity and Distance

src/main/java/org/apache/commons/text/similarity/IntersectionResult.java, src/main/java/org/apache/commons/text/similarity/IntersectionSimilarity.java, src/test/java/org/apache/commons/text/similarity/IntersectionResultTest.java, src/test/java/org/apache/commons/text/similarity/IntersectionSimilarityTest.java
This class adds a generic Similarity measure that allows the user to define how a `CharSequence` is split into a `Set`. The two sets are then compared and the results returned.
=> TEXT-155: Add a generic OverlapSimilarity measure

src/main/java/org/apache/commons/text/similarity/package-info.java
Thanks for the library! Noticed an extra 's' in 'Longest Commons Subsequence Distance' in the javadocs for `org.apache.commons.text.similarity`.
Changes:
"Longest Commons Subsequence Distance" -> "Longest Common Subsequence Distance"
=> (doc) Fix typo in similarity package docs

pom.xml, src/changes/changes.xml, src/main/java/org/apache/commons/text/lookup/DefaultStringLookup.java, src/main/java/org/apache/commons/text/lookup/DnsStringLookup.java, src/main/java/org/apache/commons/text/lookup/InetAddressKeys.java, src/main/java/org/apache/commons/text/lookup/StringLookupFactory.java, src/test/java/org/apache/commons/text/StringSubstitutorWithInterpolatorStringLookupTest.java, src/test/java/org/apache/commons/text/lookup/DefaultStringLookupTest.java, src/test/java/org/apache/commons/text/lookup/DnsStringLookupTest.java, src/test/java/org/apache/commons/text/lookup/StringLookupFactoryTest.java
=> [TEXT-170] Add String lookup for host names and IP addresses

src/main/java/org/apache/commons/text/lookup/ScriptStringLookup.java, src/test/java/org/apache/commons/text/lookup/ScriptStringLookupTest.java
The usage of ":" can be pretty usefull for inside a ScriptStringLookup
For example ternary operations : 
`${script:javascript:'${myKey:-}' == '' ? 'Not Present' : 'Present' }`
Today it's not possible to do that because the lookup only expect one ":" 
`final String[] keys = key.split(SPLIT_STR);`
But we can limit the number of split to two:
`final String[] keys = key.split(SPLIT_STR, 2);`
Thanks a lot
=> Text 174: ScriptStringLookup does not accept ":"

src/main/java/org/apache/commons/text/CaseUtils.java
=> [TEXT-184] simplify if in CaseUtils

src/changes/changes.xml, src/main/java/org/apache/commons/text/similarity/JaccardSimilarity.java, src/test/java/org/apache/commons/text/similarity/JaccardDistanceTest.java, src/test/java/org/apache/commons/text/similarity/JaccardSimilarityTest.java
Now [text] will behave the same way as other libraries (Simmetrics, javastringsimilarity). Fixes the behaviour reported by other dev in https://github.com/apache/commons-text/pull/103#discussion_r263988298.
Cheers
Bruno
=> [TEXT-158]: empty strings must have similarity of 1, and distance of 0 (i.e. identical)

pom.xml, src/changes/changes.xml
Apache Jena did something similar a few days ago. But I used this post to refresh on the changes in JVM 15, and copied the dependencies (checked in search.maven.org too to confirm these are the latest versions): https://golb.hplar.ch/2020/04/java-javascript-engine.html
=> [TEXT-187] add graalvm dependencies in test scope

src/main/java/org/apache/commons/text/StrSubstitutor.java, src/main/java/org/apache/commons/text/StrTokenizer.java, src/main/java/org/apache/commons/text/StringTokenizer.java, src/test/java/org/apache/commons/text/diff/ReplacementsFinderTest.java
* Remove redundant initializer
*  Use Empty array
=> Minor Improvements

src/changes/changes.xml, src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java, src/test/java/org/apache/commons/text/similarity/JaroWinklerDistanceTest.java
Fixed JaroWinklerDistance to be in line with Javadoc and expected output.
JaroWinklerDistance was returning incorrectly with the same values as the JaroWinklerSimilarity class.
JaroWinklerDistance was updated to return the correct 1- value, and tests maintained.
=> [TEXT-191] Fixed JaroWinklerDistance returns the same values as JaroWinklerSimilarity

src/main/java/org/apache/commons/text/StringSubstitutor.java, src/site/xdoc/userguide.xml
Just read the docs for first time and found a few apostrophe mistakes  and  added 1 clarification to make Javadoc more precise.
=> apostrophes, typos and clarifications

src/main/java/org/apache/commons/text/WordUtils.java
Looks like the documentation doesn't match the actual behavior of the abbreviate method. We should update the method or the docs to match. (see line 81 of WordUtils.java).
The docs specify that "If the upper limit is lower than the lower limit, it will be adjusted to be the same as the lower limit." but the actual behavior forbids the upper limit from being lower than the lower limit.
=> (doc) update definition of upper in abbreviate method to match behavior

.github/workflows/maven.yml, pom.xml, src/changes/changes.xml
@garydgregory reverting that checkstyle change and using the default build target instead of specifying what to run on GH Actions.
=> Revert #327 change (checkstyle 9.3 to 10.2) due to JVM incompatibility. Fix GH Actions to run checkstyle.

src/main/java/org/apache/commons/text/StringEscapeUtils.java
the javadoc example for the code was wrongly escaping quotes
as a result of an incorret conversion in https://github.com/apache/commons-text/commit/0dfe9634a4578090b3b5b670ab2fe80acfa8f280 
```
jshell> org.apache.commons.text.StringEscapeUtils.escapeHtml4("\"bread\" &amp; \"butter\"")
$1 ==> "&quot;bread&quot; &amp;amp; &quot;butter&quot;"
```
=> Fix javadoc for escapeHtml4

src/main/java/org/apache/commons/text/TextStringBuilder.java, src/test/java/org/apache/commons/text/TextStringBuilderTest.java
This fixes a performance regression where allocation was only using the exact size necessary for the additional chars (resulting in buffer reallocation on each append).
=> TEXT-228: Fix TextStringBuilder to over-allocate when ensuring capacity

src/main/java/org/apache/commons/text/numbers/DoubleFormat.java, src/test/java/org/apache/commons/text/numbers/DoubleFormatTest.java
This changes the tests to fix some incompatibility between the reference DecimalFormat class and DoubleFormat when:
- The output string has a trailing .0 due to rounding (which may be omitted by DecimalFormat).
- The Double.toString output has fewer chars than the full precision output from DecimalFormat.
=> Update DoubleFormat to state it is based on Double.toString.

src/main/java/org/apache/commons/text/WordUtils.java, src/test/java/org/apache/commons/text/WordUtilsTest.java
Fixes a regression so that the `Character.isWhitespace(char)` is used instead of just the space character for the `capitalize()` and `uncapitalize()` methods in WordUtils.
=> [TEXT-175] Fix regression for determining whitespace in WordUtils

src/main/java/org/apache/commons/text/TextStringBuilder.java
continued to implement changes to Javadoc as mentioned in: https://github.com/apache/commons-text/pull/546
=> [TEXT-234] Improve TextStringBuilder documentation for new line text
