apache/commons-text

- src/main/java/org/apache/commons/text/similarity/LevenshteinDetailedDistance.java
- src/main/java/org/apache/commons/text/similarity/LevenshteinResults.java
- src/test/java/org/apache/commons/text/similarity/LevenshteinDetailedDistanceTest.java
Hello, this contains changes meant for ticket TEXT-10.
I have created a new class named LevenshteinDetailedDistance exact similar to existing class LevenshteinDistance. The additional functionality it has is to get the number of insertion, deletion and substitution count. The logic used in the new class in also same as the existing one, except, added a new function findDetailedResults which get the needed 3 counts.
First I made change to the existing class to support support the additional functionality but then I thought not to disturb the existing one, so created a new one.
Kindly review and comment. Thank you,
> TEXT-10 A more complex Levenshtein distance

- src/main/java/org/apache/commons/text/StrBuilder.java
- src/main/java/org/apache/commons/text/similarity/EditDistance.java
- src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java
- src/main/java/org/apache/commons/text/similarity/SimilarityScore.java
- src/main/java/org/apache/commons/text/similarity/SimilarityScoreFrom.java
- src/main/java/org/apache/commons/text/similarity/package-info.java
- src/test/java/org/apache/commons/text/similarity/JaroWinklerDistanceTest.java
- src/test/java/org/apache/commons/text/similarity/ParameterizedEditDistanceFromTest.java
- src/test/java/org/apache/commons/text/similarity/ParameterizedSimilarityScoreFromTest.java
@kinow 
Resolves:
https://issues.apache.org/jira/browse/TEXT-21
> TEXT-21: Have a clear distinction between Edit Distance, String Similarity, Score, Metric, etc

- src/main/java/org/apache/commons/text/similarity/LevenshteinDistance.java
Incorporating https://github.com/apache/commons-lang/commit/103b64a373256feae6ca85f2bf220e7694e48fa4#diff-3f4c835875ddc8a211c0272e8be51394
> TEXT-22: LevenshteinDistance reduce memory consumption

- src/changes/changes.xml
- src/main/java/org/apache/commons/text/StringEscapeUtils.java
- src/test/java/org/apache/commons/text/StringEscapeUtilsTest.java
@britter, @PascalSchumacher, I think this PR has the intent of the discussion in:
https://github.com/apache/commons-lang/pull/208
Jira: https://issues.apache.org/jira/browse/TEXT-28
> TEXT-28: Add XSI escape/unescape support

- src/changes/changes.xml
- src/main/java/org/apache/commons/text/StringEscapeUtils.java
- src/test/java/org/apache/commons/text/StringEscapeUtilsTest.java
@britter, @PascalSchumacher - does this accomplish the main goal of:
https://github.com/apache/commons-lang/pull/213
__Jira Reference:__ https://issues.apache.org/jira/browse/TEXT-29
> TEXT-29: Add a builder to StringEscapeUtils

- src/changes/changes.xml
- src/main/java/org/apache/commons/text/RandomStringBuilder.java
- src/main/java/org/apache/commons/text/similarity/LongestCommonSubsequence.java
- src/main/java/org/apache/commons/text/similarity/LongestCommonSubsequenceDistance.java
- src/test/java/org/apache/commons/text/similarity/LongestCommonSubsequenceDistanceTest.java
- src/test/java/org/apache/commons/text/similarity/LongestCommonSubsequenceTest.java
@kinow, do you think we need more than just this for a release. It felt in your email that you were saying that we were good to go with what we have for the most part.
Closes (?): https://issues.apache.org/jira/browse/TEXT-32
> TEXT-32: Adding LCS similarity and distance

- src/changes/changes.xml
- src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java
- src/test/java/org/apache/commons/text/similarity/JaroWinklerDistanceTest.java
@kinow, @PascalSchumacher - adding you guys to this PR for an FYI. I think it accomplishes what is necessary.
Closes: https://issues.apache.org/jira/browse/TEXT-26
__References.__
* https://github.com/apache/commons-lang/pull/148
* https://github.com/apache/lucene-solr/commit/ce19aa28c01060dafae0b60b8005a22972c7ef94
* https://issues.apache.org/jira/browse/LANG-1199
* https://issues.apache.org/jira/browse/LUCENE-1297
> TEXT-26: adding JaroWinkler changes from LUCENE-1297

- src/changes/changes.xml
- src/main/java/org/apache/commons/text/StringEscapeUtils.java
- src/main/java/org/apache/commons/text/translate/EntityArrays.java
- src/main/java/org/apache/commons/text/translate/LookupTranslator.java
- src/main/java/org/apache/commons/text/translate/SingleLookupTranslator.java
- src/test/java/org/apache/commons/text/translate/AggregateTranslatorTest.java
- src/test/java/org/apache/commons/text/translate/EntityArraysTest.java
- src/test/java/org/apache/commons/text/translate/LookupTranslatorTest.java
Directly relates to [TEXT-58](https://issues.apache.org/jira/browse/TEXT-58) and [TEXT-59](https://issues.apache.org/jira/browse/TEXT-59)
> Text 58 - All uppercase methods

- checkstyle-suppressions.xml
- src/changes/changes.xml
- src/main/java/org/apache/commons/text/StrLookup.java
- src/main/java/org/apache/commons/text/StrMatcher.java
- src/main/java/org/apache/commons/text/StrSubstitutor.java
- src/main/java/org/apache/commons/text/StrTokenizer.java
- src/main/java/org/apache/commons/text/StringEscapeUtils.java
- src/main/java/org/apache/commons/text/translate/AggregateTranslator.java
- src/main/java/org/apache/commons/text/translate/CharSequenceTranslator.java
- src/main/java/org/apache/commons/text/translate/CodePointTranslator.java
- src/main/java/org/apache/commons/text/translate/CsvTranslators.java
- src/main/java/org/apache/commons/text/translate/EntityArrays.java
- src/main/java/org/apache/commons/text/translate/JavaUnicodeEscaper.java
- src/main/java/org/apache/commons/text/translate/LookupTranslator.java
- src/main/java/org/apache/commons/text/translate/NumericEntityEscaper.java
- src/main/java/org/apache/commons/text/translate/NumericEntityUnescaper.java
- src/main/java/org/apache/commons/text/translate/OctalUnescaper.java
- src/main/java/org/apache/commons/text/translate/SingleLookupTranslator.java
- src/main/java/org/apache/commons/text/translate/SinglePassTranslator.java
- src/main/java/org/apache/commons/text/translate/UnicodeEscaper.java
- src/main/java/org/apache/commons/text/translate/UnicodeUnescaper.java
- src/main/java/org/apache/commons/text/translate/UnicodeUnpairedSurrogateRemover.java
Resolves: https://issues.apache.org/jira/browse/TEXT-65
> TEXT-65: checkstyle fixes

- src/test/java/org/apache/commons/text/translate/CsvTranslatorsTest.java
Found missing test cases for CsvTranslators in Commons Text so added them with all code coverage.
> [Junit]: Added test cases for CsvTranslators

- src/test/java/org/apache/commons/text/StrBuilderTest.java
added some missing flows to testcases plus some nice formatting for easy understanding.
> Test: Improved testcase coverage for StrBuilder

- src/main/java/org/apache/commons/text/WordUtils.java
@chtompki Please review and let me know what you think?
> TEXT-98: Remove isDelimiter and use HashSets for delimiter checks

- pom.xml
@chtompki Applied [pomsort](https://github.com/Ekryd/sortpom) . Just a single run though not added as a dependency .
> Sort pom file

- src/main/java/org/apache/commons/text/StringSubstitutor.java
Its just class name replacement, propably refactoring miss
> Update StringSubstitutor JavaDoc

- src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java
- src/test/java/org/apache/commons/text/similarity/JaroWinklerDistanceTest.java
Fixes [TEXT-130](https://issues.apache.org/jira/browse/TEXT-130) and [TEXT-131](https://issues.apache.org/jira/browse/TEXT-131).
Changes made:
* add testcase for both issues
* update existing tests to comply with definition of Jaro-Winkler Similarity
* update `JaroWinklerDistance#matches` and `JaroWinklerDistance#apply` as described in the issues
* update documentation of `JaroWinklerDistance#matches`
> Fix [TEXT-130] and [TEXT-131]

- src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java
- src/main/java/org/apache/commons/text/similarity/JaroWinklerSimilarity.java
Docs had wrong value, different from test and the formula.
> (doc) Fixed wrong value for Jaro-Winkler example

- src/main/java/org/apache/commons/text/TextStringBuilder.java
- src/main/java/org/apache/commons/text/lookup/InetAddressKeys.java
- src/main/java/org/apache/commons/text/matcher/AbstractStringMatcher.java
- src/test/java/org/apache/commons/text/StringEscapeUtilsTest.java
> [TEXT-181] Fix Javadocs

- src/main/java/org/apache/commons/text/lookup/ConstantStringLookup.java
> [TEXT-183] Make ConstantStringLookup.constantCache final

- src/main/java/org/apache/commons/text/CaseUtils.java
- src/main/java/org/apache/commons/text/ExtendedMessageFormat.java
- src/main/java/org/apache/commons/text/StrSubstitutor.java
- src/main/java/org/apache/commons/text/StringSubstitutor.java
- src/main/java/org/apache/commons/text/io/StringSubstitutorReader.java
- src/main/java/org/apache/commons/text/lookup/ConstantStringLookup.java
- src/main/java/org/apache/commons/text/lookup/DateStringLookup.java
- src/main/java/org/apache/commons/text/lookup/IllegalArgumentExceptions.java
- src/main/java/org/apache/commons/text/lookup/StringLookupFactory.java
- src/test/java/org/apache/commons/text/AlphabetConverterTest.java
- src/test/java/org/apache/commons/text/ExtendedMessageFormatTest.java
- src/test/java/org/apache/commons/text/StrLookupTest.java
- src/test/java/org/apache/commons/text/StringSubstitutorTest.java
- src/test/java/org/apache/commons/text/TextStringBuilderTest.java
- src/test/java/org/apache/commons/text/diff/ReplacementsFinderTest.java
- src/test/java/org/apache/commons/text/similarity/LongestCommonSubsequenceDistanceTest.java
- src/test/java/org/apache/commons/text/translate/EntityArraysTest.java
> [TEXT-182] Fix typos

- src/changes/changes.xml
For #172, but also move the Update entries under the comment section :+1:
> Update changes dependabot

- src/main/java/org/apache/commons/text/AlphabetConverter.java
- src/main/java/org/apache/commons/text/RandomStringGenerator.java
- src/main/java/org/apache/commons/text/similarity/CosineSimilarity.java
- src/main/java/org/apache/commons/text/similarity/IntersectionSimilarity.java
- src/main/java/org/apache/commons/text/similarity/JaroWinklerDistance.java
- src/main/java/org/apache/commons/text/similarity/JaroWinklerSimilarity.java
- src/main/java/org/apache/commons/text/translate/NumericEntityUnescaper.java
- src/test/java/org/apache/commons/text/AlphabetConverterTest.java
- src/test/java/org/apache/commons/text/StringEscapeUtilsTest.java
- src/test/java/org/apache/commons/text/similarity/IntersectionSimilarityTest.java
* Add Final
* Use StandardCharsets.UTF_8
* convert wrapper to primitive
* Use  Collections.singletonList(
> Minor Improvements

- pom.xml
- src/changes/changes.xml
#213 taking a while to rebase, so preparing a PR manually.
> Bump mockito-inline from 3.8.0 to 3.9.0

- src/main/java/org/apache/commons/text/lookup/InterpolatorStringLookup.java
Modified variable name from 'var' to 'key' to avoid confusion in future
> Remove use of restricted identifier

- spotbugs-exclude-filter.xml
- src/main/java/org/apache/commons/text/ExtendedMessageFormat.java
- src/main/java/org/apache/commons/text/io/StringSubstitutorReader.java
- making copies of mutable inputs on construction
- ignoring false positive
> TEXT-210: fixing spotbugs failures

- .github/workflows/maven.yml
Sibling of https://github.com/apache/commons-io/pull/351/
> Set permissions for GH Actions

- src/main/java/org/apache/commons/text/StringSubstitutor.java
- src/main/java/org/apache/commons/text/lookup/DefaultStringLookup.java
- src/main/java/org/apache/commons/text/lookup/StringLookupFactory.java
- src/main/java/org/apache/commons/text/lookup/XmlDecoderStringLookup.java
- src/main/java/org/apache/commons/text/lookup/XmlEncoderStringLookup.java
- src/test/java/org/apache/commons/text/lookup/StringLookupFactoryTest.java
- src/test/java/org/apache/commons/text/lookup/XmlDecoderStringLookupTest.java
- src/test/java/org/apache/commons/text/lookup/XmlEncoderStringLookupTest.java
> [TEXT-229] Add XmlEncoderStringLookup/XmlDecoderStringLookup
